### ISSUE TITLE
issue: No datasheets in Brave browser (PC and Android)

### ISSUE THREAD

**Issue by NotOnLand** [ronplanken/game-datacards#92]
### Version Number

2.2.0

### Steps to reproduce

1. Go to site
2. Choose any army
3. Search for unit datasheets
4. No datasheets found

### Expected behaviour

Only stratagem cards show for any army. I've tried disabling extensions and Brave shields for the site, also clearing site data/cache/cookies, but it only ever says "No datasheets found." Works fine in Firefox on the same device.

Brave:
![image](https://github.com/ronplanken/game-datacards/assets/11040186/2aff0567-8207-4a47-9da2-1f78431ed32b)

Firefox (expected behavior):
![image](https://github.com/ronplanken/game-datacards/assets/11040186/be708b1d-1fef-4b2d-b88a-ab6fe32901df)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ronplanken** [comment]
This does not seem to be a specific Brave issue. Using Brave browser here everything works as it should:

![image](https://github.com/ronplanken/game-datacards/assets/480918/36c6fc79-870f-4a7a-b5e7-f9f0961c3ad8)

![image](https://github.com/ronplanken/game-datacards/assets/480918/88db8b0f-185b-4fab-8742-1df35448d112)

**Comment by NotOnLand** [comment]
I uninstalled and reinstalled Brave on my computer and it works now, still not sure about mobile but I can live with it
